
const mobileDevelopmentList = [
    {
        id: 1,
        title: "To Do List App",
        description: "Mobile Dev Description",
        tagOne: "Provider and ChangeNotifier",
        tagTwo: "Databases",
        tagThree: "ListViews and ModalBottomSheet",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/1226398/pexels-photo-1226398.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 2,
        title: "Chat App",
        description: "Mobile Dev Description 2",
        tagOne: "User Authentication",
        tagTwo: "Databases",
        tagThree: "Animation Controller",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/1111369/pexels-photo-1111369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 3,
        title: "Crypto Ticker",
        description: "Mobile Dev Description 2",
        tagOne: "APIs",
        tagTwo: "Live Data",
        tagThree: "Loops",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://www.pexels.com/photo/ripple-etehereum-and-bitcoin-and-micro-sdhc-card-844124/",
    }, 
    {
        id: 4,
        title: "Weather App",
        description: "Mobile Dev Description 2",
        tagOne: "APIs",
        tagTwo: "Location Access",
        tagThree: "Async Functions",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=400",
    }, 
    {
        id: 5,
        title: "BMI Calculator",
        description: "Mobile Dev Description 2",
        tagOne: "Routing and Navigation",
        tagTwo: "Dart Math",
        tagThree: "If Statements",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/3143085/pexels-photo-3143085.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 6,
        title: "Text-based Adventure Game",
        description: "Mobile Dev Description 2",
        tagOne: "OOP",
        tagTwo: "User Input",
        tagThree: "Hiding Unusable Widgets",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/272254/pexels-photo-272254.jpeg?auto=compress&cs=tinysrgb&w=400",
    }, 
    {
        id: 7,
        title: "Quizzing App",
        description: "Mobile Dev Description 2",
        tagOne: "OOP",
        tagTwo: "Updating State",
        tagThree: "If Else Statements",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/207756/pexels-photo-207756.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 8,
        title: "Xylophone App",
        description: "Mobile Dev Description 2",
        tagOne: "Audio Playing",
        tagTwo: "User Interaction",
        tagThree: "3rd Party Packages",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/6743164/pexels-photo-6743164.jpeg?auto=compress&cs=tinysrgb&w=400s",
    }, 
    {
        id: 9,
        title: "Magic 8 Ball",
        description: "Mobile Dev Description 2",
        tagOne: "User Interaction",
        tagTwo: "Dart Math / Randomization",
        tagThree: "OOP",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/11289567/pexels-photo-11289567.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 10,
        title: "Dice",
        description: "Mobile Dev Description 2",
        tagOne: "Stateful Widgets",
        tagTwo: "User Interaction",
        tagThree: "Updating State",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/965879/pexels-photo-965879.jpeg?auto=compress&cs=tinysrgb&w=400",
    }, 



]

    
export default mobileDevelopmentList;