
const mobileDevelopmentList = [
    {
        id: 1,
        title: "To Do List App",
        description: "Mobile Dev Description",
        tagOne: "Provider and ChangeNotifier",
        tagTwo: "Databases",
        tagThree: "ListViews and ModalBottomSheet",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 2,
        title: "Chat App",
        description: "Mobile Dev Description 2",
        tagOne: "User Authentication",
        tagTwo: "Databases",
        tagThree: "Animation Controller",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 3,
        title: "Crypto Ticker",
        description: "Mobile Dev Description 2",
        tagOne: "APIs",
        tagTwo: "Live Data",
        tagThree: "Loops",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 4,
        title: "Weather App",
        description: "Mobile Dev Description 2",
        tagOne: "APIs",
        tagTwo: "Location Access",
        tagThree: "Async Functions",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 5,
        title: "BMI Calculator",
        description: "Mobile Dev Description 2",
        tagOne: "Routing and Navigation",
        tagTwo: "Dart Math",
        tagThree: "If Statements",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 6,
        title: "Text-based Adventure Game",
        description: "Mobile Dev Description 2",
        tagOne: "OOP",
        tagTwo: "User Input",
        tagThree: "Hiding Widgets",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 7,
        title: "Quizzing App",
        description: "Mobile Dev Description 2",
        tagOne: "MBT11",
        tagTwo: "MBT22",
        tagThree: "MBT33",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 8,
        title: "Quizzing App",
        description: "Mobile Dev Description 2",
        tagOne: "MBT11",
        tagTwo: "MBT22",
        tagThree: "MBT33",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 9,
        title: "Xylophone App",
        description: "Mobile Dev Description 2",
        tagOne: "MBT11",
        tagTwo: "MBT22",
        tagThree: "MBT33",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 10,
        title: "Magic 8 Ball",
        description: "Mobile Dev Description 2",
        tagOne: "MBT11",
        tagTwo: "MBT22",
        tagThree: "MBT33",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 
    {
        id: 11,
        title: "Dice",
        description: "Mobile Dev Description 2",
        tagOne: "Stateful Widgets",
        tagTwo: "User Interaction",
        tagThree: "Updating State",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
    }, 



]

    
export default mobileDevelopmentList;