
const mobileDevelopmentList = [
    {
        id: 1,
        title: "To Do List App",
        description: "Mobile Dev Description",
        tagOne: "Provider and ChangeNotifier",
        tagTwo: "Databases",
        tagThree: "ListViews and ModalBottomSheet",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/1226398/pexels-photo-1226398.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 2,
        title: "Chat App",
        description: "Allows users to instantly communicate in a chatroom",
        tagOne: "User Authentication",
        tagTwo: "Databases",
        tagThree: "Animation Controller",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/1111369/pexels-photo-1111369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 3,
        title: "Crypto Ticker",
        description: "Compares the price of several crypto currencies to the national currency chosen by the user",
        tagOne: "APIs",
        tagTwo: "Live Data",
        tagThree: "Loops",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/844124/pexels-photo-844124.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 4,
        title: "Weather App",
        description: "Gives the current weather conditions either at the users location or at a location of the user's choice",
        tagOne: "APIs",
        tagTwo: "Location Access",
        tagThree: "Async Functions",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=400",
    }, 
    {
        id: 5,
        title: "BMI Calculator",
        description: "Calculates BMI based on factors input by the user",
        tagOne: "Routing and Navigation",
        tagTwo: "Dart Math",
        tagThree: "If Statements",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/6636374/pexels-photo-6636374.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },      
    {
        id: 6,
        title: "Text-based Adventure Game",
        description: "User responds to text-based prompts and navigates a story",..
        tagOne: "OOP",
        tagTwo: "User Input",
        tagThree: "Hiding Unusable Widgets",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/272254/pexels-photo-272254.jpeg?auto=compress&cs=tinysrgb&w=400",
    }, 
    {
        id: 7,
        title: "Quizzing App",
        description: "True / False quiz structure with a set number of questions",
        tagOne: "OOP",
        tagTwo: "Updating State",
        tagThree: "If Else Statements",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/207756/pexels-photo-207756.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 8,
        title: "Xylophone App",
        description: "User can play the Xylophone with the touch of a finger",
        tagOne: "Audio Playing",
        tagTwo: "User Interaction",
        tagThree: "3rd Party Packages",
        gitURL: "https://github.com/citysushi89/small_projects/tree/main/NFLDataAnalysis",
        vidURL: "",
        imgURL: "https://images.pexels.com/photos/6743164/pexels-photo-6743164.jpeg?auto=compress&cs=tinysrgb&w=400s",
    }, 
    {
        id: 9,
        title: "Magic 8 Ball",
        description: "Magic 8 ball randomly spits out a responses after user clicks its",
        tagOne: "User Interaction",
        tagTwo: "Dart Math / Randomization",
        tagThree: "OOP",
        gitURL: "https://github.com/citysushi89/MobileDev8Ball",
        vidURL: "https://github.com/citysushi89/MobileDev8Ball/blob/main/README.md",
        imgURL: "https://images.pexels.com/photos/6253688/pexels-photo-6253688.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    }, 
    {
        id: 10,
        title: "Dice",
        description: "Randomly gets two integers from 1-6 and displays them on the dice images",
        tagOne: "Stateful Widgets",
        tagTwo: "User Interaction",
        tagThree: "Updating State",
        gitURL: "https://github.com/citysushi89/MobileDevDice",
        vidURL: "https://github.com/citysushi89/MobileDevDice/blob/main/README.md",
        imgURL: "https://images.pexels.com/photos/965879/pexels-photo-965879.jpeg?auto=compress&cs=tinysrgb&w=400",
    }, 



]

    
export default mobileDevelopmentList;